
version: '3.3'
services:
  chrome:
    image: zenika/alpine-chrome
    ports: [9222:9222]
    command: [
      --no-sandbox,
      --remote-debugging-address=0.0.0.0,
      --remote-debugging-port=9222
    ]
